export const tableData = [
    {
        key: "height",
        type: "props",
        parameterType: "String",
        desc: "组件高度",
        remark: "默认值为 '100%'",
    },
    {
        key: "enablePullDownRefresh",
        type: "props",
        parameterType: "Boolean",
        desc: "是否允许下拉刷新",
        remark: "默认值为 true",
    },
    {
        key: "onPullDownRefresh",
        type: "props",
        parameterType: "Function",
        desc: "下拉刷新回调函数",
        remark: "默认值为 null",
    },
    {
        key: "refreshFunLoading",
        type: "props",
        parameterType: "Function",
        desc: "刷新中回调函数",
        remark: "默认值为 null",
    },
    {
        key: "onReachBottomDistance",
        type: "props",
        parameterType: "Number",
        desc: "页面上拉触底事件触发时距页面底部距离",
        remark: "默认值为 20",
    },
    {
        key: "enableReachBottom",
        type: "props",
        parameterType: "Boolean",
        desc: "是否允许上拉加载",
        remark: "默认值为 false",
    },
    {
        key: "onReachBottom",
        type: "props",
        parameterType: "Function",
        desc: "上拉完成回调函数",
        remark: "默认值为 null",
    },
    {
        key: "pullDownRefreshHeight",
        type: "props",
        parameterType: "Number",
        desc: "下拉刷新的高度",
        remark: "默认值为 50",
    },
    {
        key: "refreshBackgroundColor",
        type: "props",
        parameterType: "String",
        desc: "下拉刷新背景颜色",
        remark: "默认值为 '#f7f7f7'",
    },
    {
        key: "header",
        type: "slot",
        parameterType: "",
        desc: "顶部区域",
        remark: "",
    },
    {
        key: "refreshHeader",
        type: "slot",
        parameterType: "",
        desc: "下拉刷新区域",
        remark: "",
    },
    {
        key: "loadMore",
        type: "slot",
        parameterType: "",
        desc: "加载更多区域",
        remark: "",
    },
];