export const descData = [
    {
        key: "item",
        type: "props",
        parameterType: "Object",
        desc: "需要渲染的对象",
        remark: "",
        children: [
            {
                key: "title",
                type: "props",
                parameterType: "String",
                desc: "文章标题",
                remark: "必填",
            },
            {
                key: "desc",
                type: "props",
                parameterType: "String",
                desc: "文章描述",
                remark: "",
            },
            {
                key: "img",
                type: "props",
                parameterType: "String | Array",
                desc: "文章图片",
                remark: "",
            },
            {
                key: "time",
                type: "props",
                parameterType: "String",
                desc: "文章时间",
                remark: "",
            },
            {
                key: "author",
                type: "props",
                parameterType: "String",
                desc: "文章作者",
                remark: "",
            },
            {
                key: "href",
                type: "props",
                parameterType: "String",
                desc: "文章链接",
                remark: "",
            },
            {
                key: "tag",
                type: "props",
                parameterType: "Array",
                desc: "文章标签",
                remark: "",
            },
            {
                key: "star",
                type: "props",
                parameterType: "String",
                desc: "文章收藏数",
                remark: "",
            },
            {
                key: "isVideo",
                type: "props",
                parameterType: "Boolean",
                desc: "是否为视频",
                remark: "",
            }
        ]
    },
    {
        key: "placement",
        type: "props",
        parameterType: "String",
        desc: "放置位置",
        remark: "可选 top | bottom | left | right",
    },
    {
        key: "num",
        type: "props",
        parameterType: "Number",
        desc: "显示图片数量",
        remark: "",
    },
    {
        key: "scroll",
        type: "props",
        parameterType: "Boolean",
        desc: "是否可以横向滚动",
        remark: "",
    },
    {
        key: "row",
        type: "props",
        parameterType: "Number",
        desc: "简介显示行数",
        remark: "最多 3 行",
    },
    {
        key: "show-footer",
        type: "props",
        parameterType: "Boolean",
        desc: "是否显示底部信息",
        remark: "",
    },
    {
        key: "header",
        type: "solt",
        parameterType: "",
        desc: "顶部插槽",
        remark: "",
    },
    {
        key: "image",
        type: "solt",
        parameterType: "",
        desc: "图片插槽",
        remark: "",
    },
    {
        key: "footer",
        type: "solt",
        parameterType: "",
        desc: "底部插槽",
        remark: "",
    },
]
