export const tableData = [
    {
        key: "value",
        type: "props",
        parameterType: "String",
        desc: "绑定值",
        remark: "可以用 v-model",
    },
    {
        key: "placeholder",
        type: "props",
        parameterType: "String",
        desc: "提示词",
        remark: "",
    },
    {
        key: "codeStyle",
        type: "props",
        parameterType: "String",
        desc: "样式",
        remark: "请访问 https://github.com/hinesboy/mavonEditor/blob/HEAD/src/lib/core/hljs/lang.hljs.css.js",
    },
    {
        key: "ishljs",
        type: "props",
        parameterType: "Boolean",
        desc: "是否启用hljs高亮",
        remark: "",
    },
    {
        key: "fontSize",
        type: "props",
        parameterType: "String",
        desc: "字体大小",
        remark: "默认 14px",
    },
    {
        key: "isPreview",
        type: "props",
        parameterType: "Boolean",
        desc: "是否预览",
        remark: "",
    },
    {
        key: "previewBackground",
        type: "props",
        parameterType: "String",
        desc: "预览背景颜色",
        remark: "默认 #ffffff",
    },
    {
        key: "height",
        type: "props",
        parameterType: "String",
        desc: "高度",
        remark: "默认500px",
    },
    {
        key: "width",
        type: "props",
        parameterType: "String",
        desc: "宽度",
        remark: "默认100%",
    },
    {
        key: "markdownOption",
        type: "props",
        parameterType: "object",
        desc: "详情配置值",
        remark: "查看  https://github.com/hinesboy/mavonEditor",
    },
    {
        key: "options",
        type: "props",
        parameterType: "String",
        desc: "更多配置项 不是在 markdownOption 中配置的",
        remark: "查看 https://www.npmjs.com/package/mavon-editor",
    },
    {
        key: "aiStream",
        type: "props",
        parameterType: "Boolean",
        desc: "是否为 流式输入",
        remark: "默认 false",
    },
    {
        key: "streamList",
        type: "props",
        parameterType: "Array",
        desc: "流式输入的数组",
        remark: "请注意 开启流式输入后，请勿使用 v-model 绑定数据 , 格式是 Array<{end : boolean, message : string , [key : string] : any}>",
    },
    {
        key: "@change",
        type: "methods",
        parameterType: "",
        desc: "内容改变时触发",
        remark: "",
    },
    {
        key: "@sava",
        type: "methods",
        parameterType: "",
        desc: "保存时触发",
        remark: "",
    }
]